language: ruby
rvm:
  - 2.0.0 
  - 1.9.3
  - 1.9.2
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database shanghaitest' -U postgres
bundler_args: --binstubs=./bundler_stubs
