language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database shanghaitest' -U postgres
bundler_args: --binstubs=./bundler_stubs
after_success: 
  - 'curl --data "" http://deploy.jeff.is/colby.io'
