development:
  adapter: postgresql 
  database: shanghai
  host: localhost

test:
  adapter: postgresql 
  database: shanghai-test
  host: localhost

production:
  adapter: postgresql
  database: tba
  host: localhost
  user: postgres
  password: timanous
