development:
  adapter: postgresql 
  database: shanghai
  host: localhost

test:
  adapter: postgresql 
  database: shanghaitest
  host: localhost

production:
  adapter: postgresql
  database: tbawhite
  host: localhost
  user: postgres
  password: timanous
